### ISSUE TITLE
multiple errors 

### ISSUE THREAD

**Issue by bucky67-gto** [opabravo/mass-bruter#1]
errors out even though paths are correct - running as root or user.

python3 mass_bruteforce.py -q -f /home/test/mass-bruter/result/masscan/masscan_test.txt
Traceback (most recent call last):
  File "/home/test/mass-bruter/mass_bruteforce.py", line 123, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/mass-bruter/mass_bruteforce.py", line 119, in main
    return brute_force(ip_and_port, ports_to_brute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/mass-bruter/mass_bruteforce.py", line 44, in brute_force
    excluded_ip_port = load_excluded()
                       ^^^^^^^^^^^^^^^
  File "/home/test/mass-bruter/utils.py", line 49, in load_excluded
    with open("settings.json", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'settings.json'

**Comment by opabravo** [comment]
Thanks for reporting the issue, I accidently closed this thread,

Just implemented a fix in 8a07712f553c23ad2326d1652a4797666bb6718b

Could you help confirm that the issue was solved?

**Comment by bucky67-gto** [comment]
That seems to have remedied the issue.  thanks
